#pragma once
// Auto-generated by obj2environment.py
// Source: iwatodai_dorm.obj
// Scale: 1.454545  Centred: True
// DO NOT EDIT — regenerate from source.

#include <nds.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const u32 iwatodai_dorm_dl_0[];

#ifdef __cplusplus
}
#endif

// --- World Bounds ---
#define IWATODAI_DORM_WORLD_OFFSET_X 2.000000f
#define IWATODAI_DORM_WORLD_OFFSET_Z 1.500000f
#define IWATODAI_DORM_WORLD_WIDTH    4.000000f
#define IWATODAI_DORM_WORLD_DEPTH    3.000000f

enum iwatodai_dorm_TexSlot {
    IWATODAI_DORM_TEX_TEXTURE = 0,
    IWATODAI_DORM_TEX_COUNT = 1
};

static const int iwatodai_dorm_tex_widths[1]  = {
    256
};
static const int iwatodai_dorm_tex_heights[1] = {
    256
};

inline void Load_iwatodai_dorm(int ids[1], const unsigned int* bitmaps[1]) {
    glGenTextures(1, &ids[0]);
    glBindTexture(GL_TEXTURE_2D, ids[0]);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, TEXTURE_SIZE_256, TEXTURE_SIZE_256, 0,
        TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
        bitmaps[0]);
}

inline void Draw_iwatodai_dorm(const int ids[1]) {
    glBindTexture(GL_TEXTURE_2D, ids[0]);  // texture.png
    glCallList((u32*)iwatodai_dorm_dl_0);
}

inline void Delete_iwatodai_dorm(int ids[1]) {
    glDeleteTextures(1, ids);
}
