#pragma once
// Auto-generated by obj2environment.py
// Source: iwatodai_dorm.obj
// DO NOT EDIT — regenerate from source.

#include <nds.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// --- World Bounds ---
#define IWATODAI_DORM_WORLD_OFFSET_X 1.750000f
#define IWATODAI_DORM_WORLD_OFFSET_Z 1.312500f
#define IWATODAI_DORM_WORLD_WIDTH    3.500000f
#define IWATODAI_DORM_WORLD_DEPTH    2.625000f

enum iwatodai_dorm_TexSlot {
    IWATODAI_DORM_TEX_TEXTURE = 0,
    IWATODAI_DORM_TEX_TREE = 1,
    IWATODAI_DORM_TEX_COUNT = 2
};

struct iwatodai_dorm_BillboardData {
    v16 x, y, z;
    v16 halfWidth, halfHeight;
    int texSlot;
    short u0, v0, u1, v1;
};

class iwatodai_dorm_Environment {
public:
    u32* displayLists[2];
    u32 dlSizes[2];
    int textureIDs[2];

    static const int BILLBOARD_COUNT = 3;
    const iwatodai_dorm_BillboardData BILLBOARDS[3] = {
        { 2592, 769, -1553, 160, 330, 1, 0, 0, 16384, 16384 },
        { 1975, 769, -1553, 160, 330, 1, 0, 0, 16384, 16384 },
        { 3656, 559, -1553, 380, 101, 1, 0, 0, 16384, 16384 },
    };

    iwatodai_dorm_Environment() {
        for (int i = 0; i < 2; i++) {
            displayLists[i] = NULL; dlSizes[i] = 0; textureIDs[i] = 0;
        }
    }

    bool load(const char* filepath, const unsigned int* bitmaps[2]) {
        FILE* file = fopen(filepath, "rb");
        if (!file) return false;

        char magic[4];
        fread(magic, 1, 4, file);
        if (magic[0] != 'E' || magic[1] != 'N' || magic[2] != 'V' || magic[3] != '1') {
            fclose(file); return false;
        }

        u32 groupCount;
        fread(&groupCount, sizeof(u32), 1, file);
        if (groupCount != 2) { fclose(file); return false; }

        for (u32 i = 0; i < groupCount; i++) {
            fread(&dlSizes[i], sizeof(u32), 1, file);
            displayLists[i] = (u32*)malloc((dlSizes[i] + 1) * sizeof(u32));
            displayLists[i][0] = dlSizes[i];
            if (dlSizes[i] > 0) fread(&displayLists[i][1], sizeof(u32), dlSizes[i], file);
        }
        fclose(file);

        if (bitmaps[0]) {
            glGenTextures(1, &textureIDs[0]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_256, TEXTURE_SIZE_256, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[0]);
        }
        if (bitmaps[1]) {
            glGenTextures(1, &textureIDs[1]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_1024, TEXTURE_SIZE_1024, 0, TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, bitmaps[1]);
        }
        return true;
    }

    void draw() {
        glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
        if (displayLists[0]) glCallList(displayLists[0]);
        glBindTexture(GL_TEXTURE_2D, textureIDs[1]);
        if (displayLists[1]) glCallList(displayLists[1]);
    }

    void drawBillboards(bool faceCamera, float camX, float camY, float camZ) {
        if (BILLBOARD_COUNT == 0) return;
        int currentSlot = -1;
        bool inQuads = false;

        for (int i = 0; i < BILLBOARD_COUNT; i++) {
            const iwatodai_dorm_BillboardData& bb = BILLBOARDS[i];
            if (bb.texSlot != currentSlot) {
                if (inQuads) { glEnd(); inQuads = false; }
                glBindTexture(GL_TEXTURE_2D, textureIDs[bb.texSlot]);
                currentSlot = bb.texSlot;
            }
            if (!inQuads) { glBegin(GL_QUADS); inQuads = true; }

            v16 rX = (v16)(4096), rY = 0, rZ = 0;
            v16 uX = 0, uY = (v16)(4096), uZ = 0;

            if (faceCamera) {
                float bx = (float)bb.x / 4096.0f;
                float bz = (float)bb.z / 4096.0f;
                float dx = camX - bx;
                float dz = camZ - bz;
                float dist = sqrt(dx*dx + dz*dz);
                if (dist > 0.001f) { dx /= dist; dz /= dist; }
                rX = (v16)(dz * 4096.0f);
                rZ = (v16)(-dx * 4096.0f);
            }

            v16 rx = mulf32(rX, bb.halfWidth);
            v16 ry = mulf32(rY, bb.halfWidth);
            v16 rz = mulf32(rZ, bb.halfWidth);
            v16 ux = mulf32(uX, bb.halfHeight);
            v16 uy = mulf32(uY, bb.halfHeight);
            v16 uz = mulf32(uZ, bb.halfHeight);

            glTexCoord2t16(bb.u0, bb.v1);
            glVertex3v16(bb.x - rx - ux, bb.y - ry - uy, bb.z - rz - uz);
            glTexCoord2t16(bb.u1, bb.v1);
            glVertex3v16(bb.x + rx - ux, bb.y + ry - uy, bb.z + rz - uz);
            glTexCoord2t16(bb.u1, bb.v0);
            glVertex3v16(bb.x + rx + ux, bb.y + ry + uy, bb.z + rz + uz);
            glTexCoord2t16(bb.u0, bb.v0);
            glVertex3v16(bb.x - rx + ux, bb.y - ry + uy, bb.z - rz + uz);
        }
        if (inQuads) glEnd();
    }

    void cleanup() {
        for (u32 i = 0; i < 2; i++) {
            if (displayLists[i]) { free(displayLists[i]); displayLists[i] = NULL; }
        }
        glDeleteTextures(2, textureIDs);
    }
};
