#pragma once
// Auto-generated by dialogue_compiler.py
// Scene: _project_assets_dialogue_demo_dlg

#include "controllers/DialogueController.h"

extern int _project_assets_dialogue_demo_dlg_dialogue_bg_slot;

// ── interaction: yukari_kenji_argument — Yukari arguing with Kenji at the gate
extern const char* _project_assets_dialogue_demo_dlg_yukari_kenji_argument_bg_names[4];
extern void (*_project_assets_dialogue_demo_dlg_yukari_kenji_argument_bg_loaders[4])();
void _project_assets_dialogue_demo_dlg_yukari_kenji_argument_load_bg(int bgIndex);
extern Dialogue _project_assets_dialogue_demo_dlg_yukari_kenji_argument_lines[18];
void _project_assets_dialogue_demo_dlg_yukari_kenji_argument_init();
void _project_assets_dialogue_demo_dlg_yukari_kenji_argument_load();
inline Dialogue* _project_assets_dialogue_demo_dlg_yukari_kenji_argument_first()
{
    return &_project_assets_dialogue_demo_dlg_yukari_kenji_argument_lines[0];
}
inline Dialogue* _project_assets_dialogue_demo_dlg_yukari_kenji_argument_vouch()
{
    return &_project_assets_dialogue_demo_dlg_yukari_kenji_argument_lines[7];
}
inline Dialogue* _project_assets_dialogue_demo_dlg_yukari_kenji_argument_side_kenji()
{
    return &_project_assets_dialogue_demo_dlg_yukari_kenji_argument_lines[12];
}
inline Dialogue* _project_assets_dialogue_demo_dlg_yukari_kenji_argument_stay_out()
{
    return &_project_assets_dialogue_demo_dlg_yukari_kenji_argument_lines[15];
}

inline void _project_assets_dialogue_demo_dlg_init_all()
{
    _project_assets_dialogue_demo_dlg_yukari_kenji_argument_init();
}
